// React infrastructure

// Re-export core types
export type {
  AnimationEasing,
  AnimationKeyframe,
  AnimationSpec,
  AnimationSpring,
  AnimationStepPosition,
  AnimationTransform2D,
  AnyVNode,
  BooleanOp,
  BoxProps,
  BoxVNode,
  CanvasProps,
  CanvasVNode,
  ChildFor,
  ChildrenFor,
  DebugOverlayConfig,
  DebugOverlayPart,
  ElasticSegment,
  Engine,
  EngineOptions,
  FlexProps,
  FlexVNode,
  Frame,
  GeometryDoc,
  GeometryNode,
  GeometryViewBox,
  GridProps,
  GridVNode,
  ImageProps,
  ImageVNode,
  InlineBoxProps,
  InlineBoxVNode,
  InlineProps,
  InlineRectProps,
  InlineRectVNode,
  InlineVNode,
  PathProps,
  PathVNode,
  RenderFramesOptions,
  RenderOptions,
  RtProps,
  RtVNode,
  RubyProps,
  RubyVNode,
  ShapeProps,
  StrokeScaling,
  SvgProps,
  SvgVNode,
  SymbolDefinition,
  SymbolProps,
  TextDecoration,
  TextDecorationLine,
  TextOnPathProps,
  TextOnPathVNode,
  TextProps,
  TextUnitAnimation,
  TextVNode,
  Transform2D,
  VNode,
  VNodeChild,
  VNodeChildrenArgs,
  VNodeFor,
  VNodeInputChildFor,
  VNodeType,
} from "@boundsvg/core";
export type { WasmModule } from "@boundsvg/core/wasm";
export type { BoundSvgProps } from "./components/boundsvg.js";
export { BoundSvg } from "./components/boundsvg.js";
export type { BoundSvgNodeComponent } from "./components/nodes.js";
// Declarative JSX phantom components
export {
  Box,
  Canvas,
  Flex,
  Grid,
  Image,
  Inline,
  InlineBox,
  InlineRect,
  Path,
  Rt,
  Ruby,
  Shape,
  Svg,
  Symbol,
  Text,
  TextOnPath,
} from "./components/nodes.js";
// Main-thread SVG render hook
export type { UseRenderToSvgResult } from "./hooks/use-render-svg.js";
export { useRenderToSvg } from "./hooks/use-render-svg.js";
// VNode conversion utility
export { toVNode, toVNodeFromChildren } from "./utils/to-vnode.js";
