import type {
  IR,
  IRGroupNode,
  IRImageNode,
  IRPathNode,
  IRRectNode,
  IRShapeNode,
  IRSvgNode,
  IRTextNode,
} from "../ir/types.js";
import type { SceneNode } from "../scene/types.js";
import type { NormalizedPropsFor, VNodeType } from "../vnode/types.js";

/** How one authored property crosses the VNode/Scene boundary. */
type VNodeSceneMappingKind = "direct" | "validated-copy" | "binary-to-data-uri";

/** Which part of the WASM request owns one Scene property. */
type SceneWasmMappingKind =
  | "node-type"
  | "node-id"
  | "layout-style"
  | "text"
  | "visual"
  | "tree"
  | "source-resolution"
  | "layered-only";

type SceneNodeFor<NodeType extends VNodeType> = Extract<SceneNode, { type: NodeType }>;
const vnodeType = {
  canvas: "Canvas",
  flex: "Flex",
  grid: "Grid",
  box: "Box",
  text: "Text",
  textOnPath: "TextOnPath",
  inline: "Inline",
  inlineBox: "InlineBox",
  inlineRect: "InlineRect",
  ruby: "Ruby",
  rt: "Rt",
  image: "Image",
  path: "Path",
  svg: "Svg",
  shape: "Shape",
  symbol: "Symbol",
} as const satisfies Record<string, VNodeType>;
type ScenePayloadKey<NodeType extends VNodeType> = Exclude<
  keyof SceneNodeFor<NodeType>,
  "type" | "children"
>;
type VNodeSceneKeyMismatch = {
  [NodeType in VNodeType]:
    | Exclude<keyof NormalizedPropsFor<NodeType>, ScenePayloadKey<NodeType>>
    | Exclude<ScenePayloadKey<NodeType>, keyof NormalizedPropsFor<NodeType>>;
}[VNodeType];

/**
 * This empty ledger is only assignable while every VNode prop has a Scene
 * field with the same name and vice versa. Value-shape transformations remain
 * explicit in {@link VNODE_TO_SCENE_MAPPING}.
 */
export const VNODE_SCENE_KEY_MISMATCH_LEDGER = {} satisfies Record<VNodeSceneKeyMismatch, true>;

const vnodeSceneIdentity = { id: "direct", meta: "direct" } as const;
const vnodeSceneHandlers = {
  onClick: "direct",
  onDoubleClick: "direct",
  onContextMenu: "direct",
  onPointerDown: "direct",
  onPointerUp: "direct",
  onPointerCancel: "direct",
  onPointerMove: "direct",
  onPointerEnter: "direct",
  onPointerLeave: "direct",
  onPointerOver: "direct",
  onPointerOut: "direct",
  onMouseDown: "direct",
  onMouseUp: "direct",
  onMouseMove: "direct",
  onMouseEnter: "direct",
  onMouseLeave: "direct",
  onMouseOver: "direct",
  onMouseOut: "direct",
  onTouchStart: "direct",
  onTouchEnd: "direct",
  onTouchMove: "direct",
} as const;
const vnodeScenePosition = {
  position: "direct",
  top: "direct",
  right: "direct",
  bottom: "direct",
  left: "direct",
} as const;
const vnodeSceneBoxModel = {
  width: "direct",
  height: "direct",
  minWidth: "direct",
  minHeight: "direct",
  maxWidth: "direct",
  maxHeight: "direct",
  aspectRatio: "direct",
  padding: "direct",
  margin: "direct",
} as const;
const vnodeSceneVisualBox = {
  background: "direct",
  boxShadow: "direct",
  borderRadius: "direct",
  borderWidth: "direct",
  borderColor: "direct",
  strokeScaling: "direct",
  strokeLinecap: "direct",
  strokeLinejoin: "direct",
  strokeDasharray: "direct",
  strokeMiterlimit: "direct",
  overflow: "direct",
  opacity: "direct",
  zIndex: "direct",
} as const;
const vnodeSceneFlexItem = {
  flexGrow: "direct",
  flexShrink: "direct",
  flexBasis: "direct",
  alignSelf: "direct",
} as const;
const vnodeSceneGridItem = { gridColumn: "direct", gridRow: "direct" } as const;
const vnodeSceneTransform = { transform: "validated-copy" } as const;
const vnodeSceneAnimation = { animate: "direct" } as const;
const vnodeSceneLayer = { layer: "direct" } as const;

type VNodeSceneMappingLedger = {
  [NodeType in VNodeType]: Record<keyof NormalizedPropsFor<NodeType>, VNodeSceneMappingKind>;
};

/** Exhaustive semantic ledger for both directions of the VNode/Scene edge. */
export const VNODE_TO_SCENE_MAPPING = {
  [vnodeType.canvas]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    width: "direct",
    height: "direct",
    background: "direct",
    debug: "direct",
    language: "direct",
  },
  [vnodeType.flex]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneBoxModel,
    ...vnodeSceneVisualBox,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    direction: "direct",
    wrap: "direct",
    alignItems: "direct",
    justifyContent: "direct",
    gap: "direct",
    rowGap: "direct",
    columnGap: "direct",
  },
  [vnodeType.grid]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneBoxModel,
    ...vnodeSceneVisualBox,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    templateColumns: "direct",
    templateRows: "direct",
    gap: "direct",
    rowGap: "direct",
    columnGap: "direct",
    alignItems: "direct",
    justifyItems: "direct",
    alignSelf: "direct",
  },
  [vnodeType.box]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneBoxModel,
    ...vnodeSceneVisualBox,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
  },
  [vnodeType.text]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneBoxModel,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    font: "direct",
    fontWeight: "direct",
    fontStyle: "direct",
    fallback: "direct",
    fontVariationSettings: "direct",
    fontFeatureSettings: "direct",
    writingMode: "direct",
    textOrientation: "direct",
    fontSizePx: "direct",
    lineHeight: "direct",
    lineHeightPx: "direct",
    letterSpacingPx: "direct",
    textIndent: "direct",
    color: "direct",
    textDecoration: "direct",
    textStroke: "direct",
    textStrokeWidth: "direct",
    textStrokeLinecap: "direct",
    textStrokeLinejoin: "direct",
    textStrokeDasharray: "direct",
    textStrokeMiterlimit: "direct",
    textStrokes: "direct",
    textShadows: "direct",
    wrap: "direct",
    whiteSpace: "direct",
    tabSize: "direct",
    flowExclusions: "direct",
    flowMinRegionWidthPx: "direct",
    fit: "direct",
    maxLines: "direct",
    ellipsis: "direct",
    textAlign: "direct",
    preferredFrame: "direct",
    language: "direct",
    hangingPunctuation: "direct",
    minFontSizePx: "direct",
    shrinkEpsilonPx: "direct",
    shrinkMaxIterations: "direct",
    maxFontSizePx: "direct",
    growEpsilonPx: "direct",
    growMaxIterations: "direct",
    opacity: "direct",
    zIndex: "direct",
    animateUnits: "direct",
  },
  [vnodeType.textOnPath]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    d: "direct",
    width: "direct",
    height: "direct",
    font: "direct",
    fallback: "direct",
    fontWeight: "direct",
    fontStyle: "direct",
    fontVariationSettings: "direct",
    fontFeatureSettings: "direct",
    fontSizePx: "direct",
    letterSpacingPx: "direct",
    language: "direct",
    color: "direct",
    startOffsetPx: "direct",
    textAnchor: "direct",
    pathDirection: "direct",
    pathNormal: "direct",
    pathOffsetPx: "direct",
    pathFit: "direct",
    pathOverflow: "direct",
    textStroke: "direct",
    textStrokeWidth: "direct",
    textStrokeLinecap: "direct",
    textStrokeLinejoin: "direct",
    textStrokeDasharray: "direct",
    textStrokeMiterlimit: "direct",
    textStrokes: "direct",
    textShadows: "direct",
    textDecoration: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
    animateUnits: "direct",
  },
  [vnodeType.inline]: {
    font: "direct",
    fallback: "direct",
    fontWeight: "direct",
    fontStyle: "direct",
    fontVariationSettings: "direct",
    fontFeatureSettings: "direct",
    textOrientation: "direct",
    textCombineUpright: "direct",
    fontSizePx: "direct",
    letterSpacingPx: "direct",
    color: "direct",
    textStrokes: "direct",
    textShadows: "direct",
    textDecoration: "direct",
    language: "direct",
    paddingInline: "direct",
    background: "direct",
    borderColor: "direct",
    borderWidth: "direct",
    borderRadius: "direct",
    animate: "direct",
  },
  [vnodeType.inlineBox]: {
    font: "direct",
    fallback: "direct",
    fontWeight: "direct",
    fontStyle: "direct",
    fontSizePx: "direct",
    letterSpacingPx: "direct",
    color: "direct",
    textDecoration: "direct",
    language: "direct",
    paddingInline: "direct",
    background: "direct",
    borderColor: "direct",
    borderWidth: "direct",
    borderRadius: "direct",
    animate: "direct",
  },
  [vnodeType.inlineRect]: {
    inlineSizePx: "direct",
    blockSizePx: "direct",
    advancePx: "direct",
    blockAlign: "direct",
    color: "direct",
    borderRadiusPx: "direct",
    opacity: "direct",
    paintOrder: "direct",
    animate: "direct",
  },
  [vnodeType.ruby]: {
    rubyPosition: "direct",
    rubyAlign: "direct",
    rubyGapPx: "direct",
    rubyOffsetPx: "direct",
    rubyLineSizing: "direct",
  },
  [vnodeType.rt]: {
    font: "direct",
    fallback: "direct",
    fontWeight: "direct",
    fontStyle: "direct",
    fontVariationSettings: "direct",
    fontFeatureSettings: "direct",
    fontSizePx: "direct",
    lineHeight: "direct",
    lineHeightPx: "direct",
    letterSpacingPx: "direct",
    color: "direct",
    textDecoration: "direct",
    language: "direct",
    textOrientation: "direct",
  },
  [vnodeType.image]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    src: "binary-to-data-uri",
    mediaType: "direct",
    width: "direct",
    height: "direct",
    objectFit: "direct",
    objectPosition: "direct",
    borderRadius: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
  },
  [vnodeType.path]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    d: "direct",
    width: "direct",
    height: "direct",
    fill: "direct",
    stroke: "direct",
    strokeWidth: "direct",
    strokeScaling: "direct",
    fillRule: "direct",
    strokeLinecap: "direct",
    strokeLinejoin: "direct",
    strokeDasharray: "direct",
    strokeMiterlimit: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
  },
  [vnodeType.svg]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    ...vnodeSceneLayer,
    content: "direct",
    width: "direct",
    height: "direct",
    preserveAspectRatio: "direct",
    contentIdPrefix: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
  },
  [vnodeType.shape]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    width: "direct",
    height: "direct",
    layer: "direct",
    fill: "direct",
    stroke: "direct",
    strokeWidth: "direct",
    fillRule: "direct",
    strokeLinecap: "direct",
    strokeLinejoin: "direct",
    strokeDasharray: "direct",
    strokeMiterlimit: "direct",
    preserveAspectRatio: "direct",
    emitPartIds: "direct",
    partPaint: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
    geometry: "direct",
    geometryId: "direct",
  },
  [vnodeType.symbol]: {
    ...vnodeSceneIdentity,
    ...vnodeSceneHandlers,
    ...vnodeScenePosition,
    ...vnodeSceneFlexItem,
    ...vnodeSceneGridItem,
    ...vnodeSceneTransform,
    ...vnodeSceneAnimation,
    width: "direct",
    height: "direct",
    layer: "direct",
    fill: "direct",
    stroke: "direct",
    strokeWidth: "direct",
    fillRule: "direct",
    strokeLinecap: "direct",
    strokeLinejoin: "direct",
    strokeDasharray: "direct",
    strokeMiterlimit: "direct",
    preserveAspectRatio: "direct",
    emitPartIds: "direct",
    partPaint: "direct",
    opacity: "direct",
    zIndex: "direct",
    margin: "direct",
    symbol: "direct",
    symbolId: "direct",
  },
} as const satisfies VNodeSceneMappingLedger;

const wasmIdentity = { id: "node-id", meta: "visual" } as const;
const wasmHandlers = {
  onClick: "visual",
  onDoubleClick: "visual",
  onContextMenu: "visual",
  onPointerDown: "visual",
  onPointerUp: "visual",
  onPointerCancel: "visual",
  onPointerMove: "visual",
  onPointerEnter: "visual",
  onPointerLeave: "visual",
  onPointerOver: "visual",
  onPointerOut: "visual",
  onMouseDown: "visual",
  onMouseUp: "visual",
  onMouseMove: "visual",
  onMouseEnter: "visual",
  onMouseLeave: "visual",
  onMouseOver: "visual",
  onMouseOut: "visual",
  onTouchStart: "visual",
  onTouchEnd: "visual",
  onTouchMove: "visual",
} as const;
const wasmPosition = {
  position: "layout-style",
  top: "layout-style",
  right: "layout-style",
  bottom: "layout-style",
  left: "layout-style",
} as const;
const wasmBoxModel = {
  width: "layout-style",
  height: "layout-style",
  minWidth: "layout-style",
  minHeight: "layout-style",
  maxWidth: "layout-style",
  maxHeight: "layout-style",
  aspectRatio: "layout-style",
  padding: "layout-style",
  margin: "layout-style",
} as const;
const wasmVisualBox = {
  background: "visual",
  boxShadow: "visual",
  borderRadius: "visual",
  borderWidth: "visual",
  borderColor: "visual",
  strokeScaling: "visual",
  strokeLinecap: "visual",
  strokeLinejoin: "visual",
  strokeDasharray: "visual",
  strokeMiterlimit: "visual",
  overflow: "visual",
  opacity: "visual",
  zIndex: "visual",
} as const;
const wasmFlexItem = {
  flexGrow: "layout-style",
  flexShrink: "layout-style",
  flexBasis: "layout-style",
  alignSelf: "layout-style",
} as const;
const wasmGridItem = { gridColumn: "layout-style", gridRow: "layout-style" } as const;
const wasmTransform = { transform: "visual" } as const;
const wasmAnimation = { animate: "visual" } as const;
const wasmLayer = { layer: "layered-only" } as const;
const wasmNode = { type: "node-type" } as const;
const wasmChildren = { children: "tree" } as const;

type SceneWasmMappingLedger = {
  [NodeType in VNodeType]: Record<keyof SceneNodeFor<NodeType>, SceneWasmMappingKind>;
};

/** Exhaustive ledger for Scene -> VNode -> WASM request mapping. */
export const SCENE_TO_WASM_MAPPING = {
  [vnodeType.canvas]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    width: "layout-style",
    height: "layout-style",
    background: "visual",
    debug: "visual",
    language: "text",
  },
  [vnodeType.flex]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmBoxModel,
    ...wasmVisualBox,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    direction: "layout-style",
    wrap: "layout-style",
    alignItems: "layout-style",
    justifyContent: "layout-style",
    gap: "layout-style",
    rowGap: "layout-style",
    columnGap: "layout-style",
  },
  [vnodeType.grid]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmBoxModel,
    ...wasmVisualBox,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    templateColumns: "layout-style",
    templateRows: "layout-style",
    gap: "layout-style",
    rowGap: "layout-style",
    columnGap: "layout-style",
    alignItems: "layout-style",
    justifyItems: "layout-style",
    alignSelf: "layout-style",
  },
  [vnodeType.box]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmBoxModel,
    ...wasmVisualBox,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
  },
  [vnodeType.text]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmBoxModel,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    font: "text",
    fontWeight: "text",
    fontStyle: "text",
    fallback: "text",
    fontVariationSettings: "text",
    fontFeatureSettings: "text",
    writingMode: "text",
    textOrientation: "text",
    fontSizePx: "text",
    lineHeight: "text",
    lineHeightPx: "text",
    letterSpacingPx: "text",
    textIndent: "text",
    color: "visual",
    textDecoration: "text",
    textStroke: "visual",
    textStrokeWidth: "visual",
    textStrokeLinecap: "visual",
    textStrokeLinejoin: "visual",
    textStrokeDasharray: "visual",
    textStrokeMiterlimit: "visual",
    textStrokes: "visual",
    textShadows: "visual",
    wrap: "text",
    whiteSpace: "text",
    tabSize: "text",
    flowExclusions: "text",
    flowMinRegionWidthPx: "text",
    fit: "text",
    maxLines: "text",
    ellipsis: "text",
    textAlign: "visual",
    preferredFrame: "text",
    language: "text",
    hangingPunctuation: "text",
    minFontSizePx: "text",
    shrinkEpsilonPx: "text",
    shrinkMaxIterations: "text",
    maxFontSizePx: "text",
    growEpsilonPx: "text",
    growMaxIterations: "text",
    opacity: "visual",
    zIndex: "visual",
    animateUnits: "text",
  },
  [vnodeType.textOnPath]: {
    ...wasmNode,
    ...wasmChildren,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmAnimation,
    ...wasmLayer,
    d: "text",
    width: "layout-style",
    height: "layout-style",
    font: "text",
    fallback: "text",
    fontWeight: "text",
    fontStyle: "text",
    fontVariationSettings: "text",
    fontFeatureSettings: "text",
    fontSizePx: "text",
    letterSpacingPx: "text",
    language: "text",
    color: "visual",
    startOffsetPx: "text",
    textAnchor: "text",
    pathDirection: "text",
    pathNormal: "text",
    pathOffsetPx: "text",
    pathFit: "text",
    pathOverflow: "text",
    textStroke: "visual",
    textStrokeWidth: "visual",
    textStrokeLinecap: "visual",
    textStrokeLinejoin: "visual",
    textStrokeDasharray: "visual",
    textStrokeMiterlimit: "visual",
    textStrokes: "visual",
    textShadows: "visual",
    textDecoration: "text",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
    animateUnits: "text",
  },
  [vnodeType.inline]: {
    type: "text",
    children: "text",
    font: "text",
    fallback: "text",
    fontWeight: "text",
    fontStyle: "text",
    fontVariationSettings: "text",
    fontFeatureSettings: "text",
    textOrientation: "text",
    textCombineUpright: "text",
    fontSizePx: "text",
    letterSpacingPx: "text",
    color: "text",
    textStrokes: "text",
    textShadows: "text",
    textDecoration: "text",
    language: "text",
    paddingInline: "text",
    background: "text",
    borderColor: "text",
    borderWidth: "text",
    borderRadius: "text",
    animate: "text",
  },
  [vnodeType.inlineBox]: {
    type: "text",
    children: "text",
    font: "text",
    fallback: "text",
    fontWeight: "text",
    fontStyle: "text",
    fontSizePx: "text",
    letterSpacingPx: "text",
    color: "text",
    textDecoration: "text",
    language: "text",
    paddingInline: "text",
    background: "text",
    borderColor: "text",
    borderWidth: "text",
    borderRadius: "text",
    animate: "text",
  },
  [vnodeType.inlineRect]: {
    type: "text",
    inlineSizePx: "text",
    blockSizePx: "text",
    advancePx: "text",
    blockAlign: "text",
    color: "text",
    borderRadiusPx: "text",
    opacity: "text",
    paintOrder: "text",
    animate: "text",
  },
  [vnodeType.ruby]: {
    type: "text",
    children: "text",
    rubyPosition: "text",
    rubyAlign: "text",
    rubyGapPx: "text",
    rubyOffsetPx: "text",
    rubyLineSizing: "text",
  },
  [vnodeType.rt]: {
    type: "text",
    children: "text",
    font: "text",
    fallback: "text",
    fontWeight: "text",
    fontStyle: "text",
    fontVariationSettings: "text",
    fontFeatureSettings: "text",
    fontSizePx: "text",
    lineHeight: "text",
    lineHeightPx: "text",
    letterSpacingPx: "text",
    color: "text",
    textDecoration: "text",
    language: "text",
    textOrientation: "text",
  },
  [vnodeType.image]: {
    ...wasmNode,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    src: "source-resolution",
    mediaType: "source-resolution",
    width: "layout-style",
    height: "layout-style",
    objectFit: "visual",
    objectPosition: "visual",
    borderRadius: "visual",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
  },
  [vnodeType.path]: {
    ...wasmNode,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    d: "visual",
    width: "layout-style",
    height: "layout-style",
    fill: "visual",
    stroke: "visual",
    strokeWidth: "visual",
    strokeScaling: "visual",
    fillRule: "visual",
    strokeLinecap: "visual",
    strokeLinejoin: "visual",
    strokeDasharray: "visual",
    strokeMiterlimit: "visual",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
  },
  [vnodeType.svg]: {
    ...wasmNode,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    ...wasmLayer,
    content: "visual",
    width: "layout-style",
    height: "layout-style",
    preserveAspectRatio: "visual",
    contentIdPrefix: "visual",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
  },
  [vnodeType.shape]: {
    ...wasmNode,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    width: "layout-style",
    height: "layout-style",
    layer: "layered-only",
    fill: "visual",
    stroke: "visual",
    strokeWidth: "visual",
    fillRule: "visual",
    strokeLinecap: "visual",
    strokeLinejoin: "visual",
    strokeDasharray: "visual",
    strokeMiterlimit: "visual",
    preserveAspectRatio: "visual",
    emitPartIds: "visual",
    partPaint: "visual",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
    geometry: "source-resolution",
    geometryId: "source-resolution",
  },
  [vnodeType.symbol]: {
    ...wasmNode,
    ...wasmIdentity,
    ...wasmHandlers,
    ...wasmPosition,
    ...wasmFlexItem,
    ...wasmGridItem,
    ...wasmTransform,
    ...wasmAnimation,
    width: "layout-style",
    height: "layout-style",
    layer: "layered-only",
    fill: "visual",
    stroke: "visual",
    strokeWidth: "visual",
    fillRule: "visual",
    strokeLinecap: "visual",
    strokeLinejoin: "visual",
    strokeDasharray: "visual",
    strokeMiterlimit: "visual",
    preserveAspectRatio: "visual",
    emitPartIds: "visual",
    partPaint: "visual",
    opacity: "visual",
    zIndex: "visual",
    margin: "layout-style",
    symbol: "source-resolution",
    symbolId: "source-resolution",
  },
} as const satisfies SceneWasmMappingLedger;

type RustIrMappingKind = "wire" | "warning-rehydration";

/** Exhaustive public shape of the Rust IR output after warning rehydration. */
export const RUST_IR_TO_PUBLIC_IR_MAPPING = {
  ir: {
    root: "wire",
    drawOrder: "wire",
    width: "wire",
    height: "wire",
    debug: "wire",
    warnings: "warning-rehydration",
  } satisfies Record<keyof IR, RustIrMappingKind>,
  group: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    children: "wire",
    opacity: "wire",
    transform: "wire",
    animation: "wire",
    meta: "wire",
    boxShadow: "wire",
    clipPath: "wire",
    clipBorderRadius: "wire",
    on: "wire",
  } satisfies Record<keyof IRGroupNode, RustIrMappingKind>,
  rect: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    fill: "wire",
    gradient: "wire",
    stroke: "wire",
    strokeWidth: "wire",
    strokeLinecap: "wire",
    strokeLinejoin: "wire",
    strokeDasharray: "wire",
    strokeMiterlimit: "wire",
    borderRadius: "wire",
    strokeScaling: "wire",
  } satisfies Record<keyof IRRectNode, RustIrMappingKind>,
  text: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    lines: "wire",
    font: "wire",
    fontFallback: "wire",
    fontSizePx: "wire",
    fontWeight: "wire",
    fontStyle: "wire",
    letterSpacingPx: "wire",
    fontVariationSettings: "wire",
    fontFeatureSettings: "wire",
    color: "wire",
    textAlign: "wire",
    layoutBox: "wire",
    writingMode: "wire",
    language: "wire",
    lineHeightPx: "wire",
    textLayoutKind: "wire",
    textPath: "wire",
    sourceText: "wire",
    displayText: "wire",
    glyphPaths: "wire",
    unitMap: "wire",
    unitAnimation: "wire",
    unitAnimationSamples: "wire",
    stroke: "wire",
    strokeWidth: "wire",
    strokeLinecap: "wire",
    strokeLinejoin: "wire",
    strokeDasharray: "wire",
    strokeMiterlimit: "wire",
    strokes: "wire",
    shadows: "wire",
    textDecorations: "wire",
    on: "wire",
  } satisfies Record<keyof IRTextNode, RustIrMappingKind>,
  image: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    src: "wire",
    preserveAspectRatio: "wire",
    on: "wire",
  } satisfies Record<keyof IRImageNode, RustIrMappingKind>,
  path: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    pathData: "wire",
    fill: "wire",
    stroke: "wire",
    strokeWidth: "wire",
    fillRule: "wire",
    strokeLinecap: "wire",
    strokeLinejoin: "wire",
    strokeDasharray: "wire",
    strokeMiterlimit: "wire",
    strokeScaling: "wire",
    on: "wire",
  } satisfies Record<keyof IRPathNode, RustIrMappingKind>,
  svg: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    svgContent: "wire",
    svgViewBox: "wire",
    preserveAspectRatio: "wire",
    on: "wire",
  } satisfies Record<keyof IRSvgNode, RustIrMappingKind>,
  shape: {
    type: "wire",
    nodeId: "wire",
    bbox: "wire",
    shapeParts: "wire",
    fill: "wire",
    stroke: "wire",
    strokeWidth: "wire",
    fillRule: "wire",
    strokeLinecap: "wire",
    strokeLinejoin: "wire",
    strokeDasharray: "wire",
    strokeMiterlimit: "wire",
    on: "wire",
  } satisfies Record<keyof IRShapeNode, RustIrMappingKind>,
} as const;
