/**
 * Freezes the number-to-string semantics used for SVG attribute values.
 *
 * fixtures/conformance/num-format-cases.json is the shared contract: any other
 * emitter implementation must reproduce every expected column byte-for-byte,
 * and this suite pins the current TS behavior against it. The fixture's
 * `rules` metadata records which formatting rule each emit site uses.
 *
 * Expected values were generated by executing the JS semantics, never
 * hand-written; the assertions below re-derive them on every run, so the
 * fixture cannot silently drift from the implementation.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";
import { FatalError } from "../../src/errors.js";
import { formatNumber } from "../../src/svg/utils.js";
import { transformToSvg } from "../../src/transform.js";

const CASES_MIN = 50;

type NumFormatCase = {
  input: string;
  expected: string;
  expectedRound2: string;
  expectedRound4: string;
};

type NumFormatFixture = {
  description: string;
  rules: Array<{ id: string; algorithm: string; expectedField: string; sites: string[] }>;
  cases: NumFormatCase[];
};

const fixturePath = path.resolve(
  __dirname,
  "../../../../fixtures/conformance/num-format-cases.json",
);
const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8")) as NumFormatFixture;

describe("SVG number formatting fixture", () => {
  it(`covers at least ${CASES_MIN} cases with unique canonical inputs`, () => {
    expect(fixture.cases.length).toBeGreaterThanOrEqual(CASES_MIN);
    const inputs = fixture.cases.map((formatCase) => formatCase.input);
    expect(new Set(inputs).size).toBe(inputs.length);
  });

  it("declares the three recorded formatting rules", () => {
    expect(fixture.rules.map((rule) => rule.id).sort()).toEqual([
      "round2-string",
      "round4-string",
      "string",
    ]);
  });

  it("uses canonical inputs that parse back to the same double", () => {
    for (const formatCase of fixture.cases) {
      const value = Number(formatCase.input);
      expect(Number.isFinite(value), `input "${formatCase.input}" must be finite`).toBe(true);
      if (formatCase.input === "-0") {
        expect(Object.is(value, -0)).toBe(true);
      } else {
        // String(Number(input)) === input guarantees any language parsing the
        // shortest representation reconstructs the identical bit pattern.
        expect(String(value)).toBe(formatCase.input);
      }
    }
  });

  it("rule string: String(n) matches every expected value", () => {
    for (const formatCase of fixture.cases) {
      expect(String(Number(formatCase.input)), `String(${formatCase.input})`).toBe(
        formatCase.expected,
      );
    }
  });

  it("rule string: the transform emit path produces every expected value", () => {
    // Pins the actual production code path (transform.ts formatSvgNumber via
    // transformToSvg), not just the String() builtin — a rewrite of the
    // private formatter to e.g. toFixed would pass the assertion above and
    // must fail here. rotate() is used because it emits for every finite
    // value, including 0 and -0 (translate is skipped when zero).
    for (const formatCase of fixture.cases) {
      expect(
        transformToSvg({ rotateDeg: Number(formatCase.input) }),
        `transformToSvg rotate ${formatCase.input}`,
      ).toBe(`rotate(${formatCase.expected} 0 0)`);
    }
  });

  it("rule round2-string: formatNumber(n) matches every expected value", () => {
    for (const formatCase of fixture.cases) {
      expect(formatNumber(Number(formatCase.input)), `formatNumber(${formatCase.input})`).toBe(
        formatCase.expectedRound2,
      );
    }
  });

  it("rule round4-string: formatNumber(n, 4) matches every expected value", () => {
    for (const formatCase of fixture.cases) {
      expect(
        formatNumber(Number(formatCase.input), 4),
        `formatNumber(${formatCase.input}, 4)`,
      ).toBe(formatCase.expectedRound4);
    }
  });

  it("formatNumber rejects non-finite input (frozen error contract)", () => {
    for (const nonFinite of [Number.NaN, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY]) {
      expect(() => formatNumber(nonFinite)).toThrow(FatalError);
    }
  });

  it("covers the required boundary inputs", () => {
    const inputs = new Set(fixture.cases.map((formatCase) => formatCase.input));
    for (const required of [
      "-0",
      "0.30000000000000004",
      "100000000000000000000",
      "1e+21",
      "0.000001",
      "1e-7",
      "2.220446049250313e-16",
      "9007199254740991",
      "5e-324",
      "0.5",
      "12.75",
      "33.333333333333336",
    ]) {
      expect(inputs.has(required), `fixture must include ${required}`).toBe(true);
    }
  });
});
